### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tanmengwen** [ygling2008/direct_edge_imu#2]
First, thank you for you to release this good project. I can't wait to run it on my PC, but I got this error below:

src/direct_edge_imu/src/rosPub.h:41:37: fatal error: quadrotor_msgs/Odometry.h: No such file or directory
 #include "quadrotor_msgs/Odometry.h"

It seems that this error also happened in dense_new project, and it is commented out.

Thank you!!!!

**Comment by ygling2008** [comment]
I have added this header in the source files.

**Comment by tanmengwen** [comment]
It works!

Actually, it also has a small compiler error and I fix it by myself.
In SlamSystem::para2eigen(), cur_P0 doesn't exist. 

By the way, it seems that there is no visualization.
